### ISSUE TITLE
#feedback? CAS přihlášení pomocí přezdívky

### ISSUE THREAD

**Issue by Kechl** [ReCodEx/android-app#2]
Zdravím.
Při pokusu o přihlášení se do aplikace přes CAS jsem se zasekl ve chvíli, kdy jsem zjistil, že do pole UKCO jdou zadávat pouze číslice. Kód číselný (samozřejmě lehce dohledatelný) si nepamatuji, a tak bych implementaci možnosti zadávání své _přezdívky_ namísto čísla velmi uvítal.
:)
(Je-li to problém konkrétního zařízení či systému (Android), pak se omlouvám, nejsem zcela technicky typ. 🤓)
((Také si uvědomuji, že nyní možná stále řešíte problém s novým systémem autorizace, který před tímto má přednost. 😃))

**Comment by krulis-martin** [comment]
Dobry den,
Bohuzel, android aplikace v tuto chvili neni prioritou, Mozna se podari posunout ji o trochu dal s podporou od studentu, kteri studuji Vyvoj aplikaci pro mobilni zarizeni. My ted resime webovou cast. Dale se obavam, ze jen velmi malo lidi ma v CAS prezdivku, alespon pokud vim. Nespletl jste si CAS login s loginem do SISu?

**Comment by Kechl** [comment]
Rozumím, nevadí.
Odpovědí na otázku si nejsem jist. Místo _přezdívky_ jsem měl napsat _přihlašovací jméno_ obdržené, pardon. Nerozumím ještě školním systémům plně, jsem prostý prvák 😃.. ale myslel jsem, že _osobní číslo_ i _přidělené přihlašovací jméno_ fungují na obou portálech (SISu i CASu). V aplikaci se dá přilhásit buď pod 'panelem' **REGULAR**, nebo pod **CAS**, tak o tomto CASu jsem mluvil. Za zmatenost se omlouvám.

**Comment by krulis-martin** [comment]
CAS je centralni autorizacni system univerzity. Pomoci CAS se jde prihlasit do SISu i do jinych univerzitnich aplikaci. Vetsina lidi ma v CAS jako prihlasovaci jmeno jen UKCO. SIS ma vedle toho jeste alfanumericke loginy slozene z prijmeni a jmena.

**Comment by SemaiCZE** [comment]
V planu je prihlasovani primo pomoci webove stranky CAS jako je to ve webove aplikaci. Tam pak take bude fungovat krome UKCO cisla i textovy identifikator.
Tato issue je dusledek #1, proto zaviram.
